// Code generated by go tool dist; DO NOT EDIT.

package cfg

const DefaultPkgConfig = `pkg-Config`

func DefaultCC(goos, goarch string) string {
	switch goos + `/` + goarch {
	}
	return "clang"
}
func DefaultCXX(goos, goarch string) string {
	switch goos + `/` + goarch {
	}
	return "clang++"
}
